#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zola"
name = "Zola"
description.en = "Static site generator"
description.fr = "Générateur de site statique"

version = "0.19.2~ynh2"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
website = "https://www.getzola.org/"
admindoc = "https://www.getzola.org/documentation/getting-started/overview/"
code = "https://github.com/getzola/zola"
fund = "https://github.com/sponsors/Keats"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = [ "amd64" ]
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "30M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.auto_rebuild]
    ask.en = "Auto-rebuild?"
    help.en = "Do you want Zola to automatically rebuild your website when files have been modified?"
    type = "boolean"
    default = true

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz"
    sha256 = "0798e69b86c628ddcb264ebd86c8cc8dce7670b9049060bf94faa73f6857cd9c"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^zola-v.*-x86_64-unknown-linux-gnu.tar.gz$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
