#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zola"
name = "Zola"
description.en = "Static site generator"
description.fr = "Générateur de site statique"

version = "0.23.2~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
website = "https://www.getzola.org/"
admindoc = "https://www.getzola.org/documentation/getting-started/overview/"
code = "https://github.com/getzola/zola"
fund = "https://github.com/sponsors/Keats"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true

ldap = false
sso = false

disk = "180M"
ram.build = "80M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.auto_rebuild]
    ask.en = "Auto-rebuild?"
    help.en = "Do you want Zola to automatically rebuild your website when files have been modified?"
    type = "boolean"
    default = true

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/getzola/zola/releases/download/v0.23.2/zola-v0.23.2-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "e2e87de440e69524619cf6067a5bc534ff770d4ce0fc30a3c7c7b3092f17b045"
    arm64.url = "https://github.com/getzola/zola/releases/download/v0.23.2/zola-v0.23.2-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "e00a87147e2f870df42b29187452b48c660ee3d4c0dcee200af5d549870637be"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^zola-v.*-x86_64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.arm64 = "^zola-v.*-aarch64-unknown-linux-gnu.tar.gz$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
