#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zola"
name = "Zola"
description.en = "A static site generator"
description.fr = "Un générateur de site statique"

version = "0.18.0~ynh2"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
website = "https://www.getzola.org/"
admindoc = "https://www.getzola.org/documentation/getting-started/overview/"
code = "https://github.com/getzola/zola"
fund = "https://github.com/sponsors/Keats"

[integration]
yunohost = ">= 11.2"
architectures = [ "amd64" ]
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "30M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/getzola/zola/releases/download/v0.18.0/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz"
    sha256 = "521ca7990b60e1270df807e01cbeb1ce69ef099745883b7929a4944cd5625d3e"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^zola-v.*-x86_64-unknown-linux-gnu.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
