#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zola"
name = "Zola"
description.en = "A static site generator"
description.fr = "Un générateur de site statique"

version = "0.19.1~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
website = "https://www.getzola.org/"
admindoc = "https://www.getzola.org/documentation/getting-started/overview/"
code = "https://github.com/getzola/zola"
fund = "https://github.com/sponsors/Keats"

[integration]
yunohost = ">= 11.2"
architectures = [ "amd64" ]
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "30M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.auto_rebuild]
    ask.en = "Auto-rebuild?"
    help.en = "Do you want Zola to automatically rebuild your website when files have been modified?"
    type = "boolean"
    default = true

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/getzola/zola/releases/download/v0.19.1/zola-v0.19.1-x86_64-unknown-linux-gnu.tar.gz"
    sha256 = "90b49041ccab8fbb6955914c41e72774771a6dcbd58936fb107aa8409cb44aa0"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^zola-v.*-x86_64-unknown-linux-gnu.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
