#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.auto_rebuild = "true"

    test_upgrade_from.ee5e9c24bb22c7334a5c62390f391942e83c530d.name = "Upgrade from 0.20.0~ynh2"
