#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#REMOVEME? ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

#=================================================
# SPECIFIC GETTERS
#=================================================

get__auto_rebuild() {

    auto_rebuild=$(ynh_app_setting_get --key=auto_rebuild)

    echo "$auto_rebuild"
}

#=================================================
# SPECIFIC SETTERS
#=================================================

set__auto_rebuild() {

    if $auto_rebuild; then
        systemctl enable "$app.path" --quiet
        systemctl start "$app.path"
    else
        systemctl disable "$app.path" --quiet
        systemctl stop "$app.path"
    fi

    ynh_app_setting_set --key=auto_rebuild --value="$auto_rebuild"
}

#=================================================
ynh_app_config_run "$1"
