#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

auto_rebuild=$(convert_bool "$YNH_APP_ARG_AUTO_REBUILD")
ynh_app_setting_set --key=auto_rebuild --value="$auto_rebuild"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ls -l "$install_dir"

chmod +x "$install_dir/zola"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.toml" --destination="$install_dir/config.toml"

mkdir -p "$install_dir/content" "$install_dir/static" "$install_dir/templates" "$install_dir/themes/yunohost/templates"

ynh_config_add --template="theme.toml" --destination="$install_dir/themes/yunohost/theme.toml"
ynh_config_add --template="theme.html" --destination="$install_dir/themes/yunohost/templates/index.html"

ynh_config_add --template="_index.md" --destination="$install_dir/content/_index.md"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

if $auto_rebuild; then
    ynh_config_add_systemd --template="systemd.path" --destination="/etc/systemd/system/$app.path"  
fi

yunohost service add "$app" --description="Static site generator" --log="/var/log/$app/$app.log" --test_status="systemctl is-active $app.path"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

if $auto_rebuild; then
    ynh_systemctl --service="$app.path" --action="start"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
