#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/zola"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.toml" --destination="$install_dir/config.toml"

mkdir -p "$install_dir/content" "$install_dir/static" "$install_dir/templates" "$install_dir/themes/yunohost/templates"

ynh_config_add --template="theme.toml" --destination="$install_dir/themes/yunohost/theme.toml"
ynh_config_add --template="theme.html" --destination="$install_dir/themes/yunohost/templates/index.html"
ynh_config_add --template="_index.md" --destination="$install_dir/content/_index.md"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
ynh_config_add_systemd --service="${app}-path" --template="path.service"

yunohost service add "$app" --description="Static site generator" --log="/var/log/$app/$app.log" --test_status="systemctl is-active $app.path"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

if [ $auto_rebuild == "true" ]; then
    systemctl --service="$app-path" --action="start"
fi

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
